import XCTest
@testable import QuillCodeTools

final class ProjectInitScaffolderTests: XCTestCase {
    func testSwiftProjectGoldenMarkdown() {
        let signals = ProjectInitScaffolder.Signals(
            languages: [.swift], hasMakefile: false, topLevelDirectories: ["Sources", "Tests"]
        )
        XCTAssertEqual(ProjectInitScaffolder.scaffold(name: "QuillCode", signals: signals), """
        # QuillCode

        > Generated by QuillCode /init. Edit freely — this file is the project's agent
        > instructions (AGENTS.md, the Codex/Claude-CLI convention).

        ## Project overview

        QuillCode is a Swift project.

        ## Build

        - `swift build`

        ## Test

        - `swift test`

        ## Project layout

        - `Sources/`
        - `Tests/`

        ## Conventions

        - Keep changes small and focused.
        - Run the test command above before finishing.
        - Update this file when the build or test commands change.

        """)
    }

    func testMultiLanguageListsEachBuildAndTestCommand() {
        let signals = ProjectInitScaffolder.Signals(languages: [.swift, .node], hasMakefile: true)
        let markdown = ProjectInitScaffolder.scaffold(name: "App", signals: signals)
        XCTAssertTrue(markdown.contains("App is a Swift and Node.js project."))
        XCTAssertTrue(markdown.contains("- `swift build`"))
        // Node has no standard build step, so it is not asserted as one (install != build).
        XCTAssertFalse(markdown.contains("npm install"))
        XCTAssertTrue(markdown.contains("- `make` (a Makefile is present)"))
        XCTAssertTrue(markdown.contains("- `swift test`"))
        XCTAssertTrue(markdown.contains("- `npm test`"))
    }

    func testEmptySignalsStillProduceANonEmptySkeleton() {
        let markdown = ProjectInitScaffolder.scaffold(name: "Mystery", signals: ProjectInitScaffolder.Signals())
        // Never empty — the instruction loader drops blank files, so a skeleton must load.
        XCTAssertFalse(markdown.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
        XCTAssertTrue(markdown.contains("No build step detected"))
        XCTAssertTrue(markdown.contains("No test command detected"))
        XCTAssertTrue(markdown.contains("Document the key directories here"))
    }

    func testIsDeterministicForIdenticalSignals() {
        let signals = ProjectInitScaffolder.Signals(languages: [.python, .go], topLevelDirectories: ["cmd", "internal"])
        XCTAssertEqual(
            ProjectInitScaffolder.scaffold(name: "svc", signals: signals),
            ProjectInitScaffolder.scaffold(name: "svc", signals: signals)
        )
    }
}
