import Foundation

enum MCPServerToolCatalog {
    static let runToolName = "codex"
    static let replyToolName = "codex-reply"

    static let listResult: CLIJSONValue = .object([
        "tools": .array([runTool, replyTool])
    ])

    static func callResult(
        threadID: UUID?,
        content: String,
        isError: Bool = false
    ) -> CLIJSONValue {
        let identifier = threadID?.uuidString.lowercased() ?? ""
        return .object([
            "content": .array([.object([
                "type": .string("text"),
                "text": .string(content)
            ])]),
            "structuredContent": .object([
                "threadId": .string(identifier),
                "content": .string(content)
            ]),
            "isError": .bool(isError)
        ])
    }

    static func error(_ message: String, threadID: UUID? = nil) -> CLIJSONValue {
        callResult(threadID: threadID, content: message, isError: true)
    }

    private static let outputSchema: CLIJSONValue = .object([
        "type": .string("object"),
        "properties": .object([
            "threadId": .object(["type": .string("string")]),
            "content": .object(["type": .string("string")])
        ]),
        "required": .array([.string("threadId"), .string("content")])
    ])

    private static let runTool: CLIJSONValue = .object([
        "name": .string(runToolName),
        "title": .string("QuillCode"),
        "description": .string(
            "Run a QuillCode session. Accepts configuration parameters matching the Codex MCP tool."
        ),
        "inputSchema": .object([
            "type": .string("object"),
            "properties": .object(runToolProperties),
            "required": .array([.string("prompt")]),
            "additionalProperties": .bool(false)
        ]),
        "outputSchema": outputSchema
    ])

    private static let runToolProperties: [String: CLIJSONValue] = {
        var properties: [String: CLIJSONValue] = [
            "config": .object([
                "description": .string(
                    "Individual config settings that override ~/.quillcode/config.toml."
                ),
                "type": .string("object"),
                "additionalProperties": .bool(true)
            ]),
            "cwd": .object([
                "description": .string(
                    "Working directory for the session. Relative paths resolve against the server process cwd."
                ),
                "type": .string("string")
            ]),
            "model": .object([
                "description": .string("Optional override for the TrustedRouter model name."),
                "type": .string("string")
            ]),
            "prompt": .object([
                "description": .string("The *initial user prompt* to start the QuillCode conversation."),
                "type": .string("string")
            ])
        ]
        addAliases(
            MCPServerRunInput.approvalPolicyArgumentAliases,
            to: &properties,
            schema: .object([
                "description": .string(
                    "Approval policy for shell commands generated by the model: `untrusted`, "
                        + "`on-failure`, `on-request`, `never`."
                ),
                "type": .string("string"),
                "enum": .array(MCPServerApprovalPolicy.allCases.map {
                    .string($0.rawValue)
                })
            ])
        )
        addAliases(
            MCPServerRunInput.baseInstructionsArgumentAliases,
            to: &properties,
            schema: stringSchema("The set of instructions to use instead of the default ones.")
        )
        addAliases(
            MCPServerRunInput.compactPromptArgumentAliases,
            to: &properties,
            schema: stringSchema("Prompt used when compacting the conversation.")
        )
        addAliases(
            MCPServerRunInput.developerInstructionsArgumentAliases,
            to: &properties,
            schema: stringSchema("Developer instructions injected as a system instruction.")
        )
        addAliases(
            MCPServerRunInput.sandboxArgumentAliases,
            to: &properties,
            schema: .object([
                "description": .string(
                    "Sandbox mode: `read-only`, `workspace-write`, or `danger-full-access`."
                ),
                "type": .string("string"),
                "enum": .array(sandboxModes.map(CLIJSONValue.string))
            ])
        )
        return properties
    }()

    private static func stringSchema(_ description: String) -> CLIJSONValue {
        .object([
            "description": .string(description),
            "type": .string("string")
        ])
    }

    private static func addAliases(
        _ aliases: [String],
        to properties: inout [String: CLIJSONValue],
        schema: CLIJSONValue
    ) {
        for alias in aliases {
            properties[alias] = schema
        }
    }

    private static let replyTool: CLIJSONValue = .object([
        "name": .string(replyToolName),
        "title": .string("QuillCode Reply"),
        "description": .string("Continue a QuillCode conversation by providing the thread id and prompt."),
        "inputSchema": .object([
            "type": .string("object"),
            "properties": .object([
                "conversationId": .object([
                    "description": .string("DEPRECATED: use threadId instead."),
                    "type": .string("string")
                ]),
                "prompt": .object([
                    "description": .string("The *next user prompt* to continue the QuillCode conversation."),
                    "type": .string("string")
                ]),
                "threadId": .object([
                    "description": .string(
                        "The thread id for this QuillCode session. Required at runtime; optional in the "
                            + "schema for clients that still send conversationId."
                    ),
                    "type": .string("string")
                ])
            ]),
            "required": .array([.string("prompt")]),
            "additionalProperties": .bool(false)
        ]),
        "outputSchema": outputSchema
    ])
    private static let sandboxModes = ["read-only", "workspace-write", "danger-full-access"]
}
