import XCTest

final class ParityTerminalRendererGateTests: QuillCodeParityTestCase {
    func testTerminalRendererKeepsEscapeSemanticsInFocusedFiles() throws {
        let rendererText = try Self.toolsSourceText(named: "TerminalOutputRenderer.swift")
        let bufferText = try Self.toolsSourceText(named: "TerminalScreenBuffer.swift")
        let controlsText = try Self.toolsSourceText(named: "TerminalScreenBufferControls.swift")
        let cellText = try Self.toolsSourceText(named: "TerminalScreenCell.swift")
        let policyText = try Self.toolsSourceText(named: "TerminalOutputAmbiguousWidthPolicy.swift")
        let widthText = try Self.toolsSourceText(named: "TerminalScreenCellWidth.swift")
        let cellMutationText = try Self.toolsSourceText(named: "TerminalScreenBufferCells.swift")
        let graphemeText = try Self.toolsSourceText(named: "TerminalScreenGraphemeClusters.swift")
        let scrollRegionText = try Self.toolsSourceText(named: "TerminalScreenBufferScrollRegion.swift")
        let scrollingText = try Self.toolsSourceText(named: "TerminalScreenBufferScrolling.swift")
        let lineMutationText = try Self.toolsSourceText(named: "TerminalScreenBufferLineMutation.swift")
        let alternateScreenText = try Self.toolsSourceText(named: "TerminalScreenBufferAlternateScreen.swift")

        XCTAssertTrue(bufferText.contains("struct TerminalScreenBuffer"))
        XCTAssertTrue(bufferText.contains("let ambiguousWidthPolicy: TerminalOutputAmbiguousWidthPolicy"))
        XCTAssertTrue(bufferText.contains("init(ambiguousWidthPolicy: TerminalOutputAmbiguousWidthPolicy = .narrow)"))
        XCTAssertTrue(bufferText.contains("mutating func feed(_ raw: String)"))
        XCTAssertTrue(bufferText.contains("static let tabStopInterval = 8"))
        XCTAssertTrue(bufferText.contains("case \"\\u{9B}\""))
        XCTAssertTrue(bufferText.contains("case \"\\u{84}\""))
        XCTAssertTrue(bufferText.contains("case \"\\u{85}\""))
        XCTAssertTrue(bufferText.contains("case \"\\u{8D}\""))
        XCTAssertTrue(bufferText.contains("case \"\\u{9D}\""))
        XCTAssertTrue(bufferText.contains("case \"P\", \"X\", \"^\", \"_\""))
        XCTAssertTrue(bufferText.contains("case \"D\":  // IND: index"))
        XCTAssertTrue(bufferText.contains("case \"E\":  // NEL: next line"))
        XCTAssertTrue(bufferText.contains("case \"c\":  // RIS: reset to initial terminal state"))
        XCTAssertTrue(bufferText.contains("mutating func reset()"))
        XCTAssertTrue(bufferText.contains("mouseModeState = TerminalMouseModeState()"))
        XCTAssertTrue(bufferText.contains("\"\\u{0B}\""))
        XCTAssertTrue(bufferText.contains("\"\\u{0C}\""))
        XCTAssertTrue(bufferText.contains("control.value < 0x20 || control.value == 0x7F"))
        XCTAssertTrue(bufferText.contains("func consumeStringControl"))
        XCTAssertTrue(cellText.contains("struct TerminalScreenCell"))
        XCTAssertTrue(policyText.contains("public enum TerminalOutputAmbiguousWidthPolicy"))
        XCTAssertTrue(policyText.contains("public static let environmentOverrideName = \"QUILLCODE_TERMINAL_AMBIGUOUS_WIDTH\""))
        XCTAssertTrue(policyText.contains("public static func automatic"))
        XCTAssertTrue(policyText.contains("isCJKLocaleIdentifier"))
        XCTAssertTrue(policyText.contains("localeIdentifierCandidate"))
        XCTAssertTrue(widthText.contains("enum TerminalScreenCellWidth"))
        XCTAssertTrue(cellMutationText.contains("mutating func clearCellCluster"))
        XCTAssertTrue(cellMutationText.contains("mutating func insertCharacters"))
        XCTAssertTrue(cellMutationText.contains("mutating func deleteCharacters"))
        XCTAssertTrue(cellMutationText.contains("mutating func eraseCharacters"))
        XCTAssertTrue(cellMutationText.contains("mutating func repeatPreviousCharacter"))
        XCTAssertTrue(graphemeText.contains("struct TerminalScreenGraphemeCluster"))
        XCTAssertTrue(graphemeText.contains("static func indexed"))
        XCTAssertTrue(controlsText.contains("mutating func applyCSI"))
        XCTAssertTrue(controlsText.contains("mutating func horizontalTab"))
        XCTAssertTrue(controlsText.contains("mutating func backwardHorizontalTab"))
        XCTAssertTrue(scrollRegionText.contains("mutating func setScrollRegion"))
        XCTAssertTrue(scrollingText.contains("mutating func scrollUp"))
        XCTAssertTrue(lineMutationText.contains("mutating func insertLines"))
        XCTAssertTrue(alternateScreenText.contains("mutating func enterAlternateScreen"))
        XCTAssertFalse(rendererText.contains("struct TerminalScreenBuffer"))
        XCTAssertFalse(rendererText.contains("mutating func applyCSI"))
        XCTAssertTrue(rendererText.contains("fixed tab stops"))
        XCTAssertTrue(rendererText.contains("static func requiresTerminalRendering"))
        XCTAssertTrue(rendererText.contains("value < 0x20 || value == 0x7F"))
        XCTAssertTrue(rendererText.contains("value == 0x84"))
        XCTAssertTrue(rendererText.contains("value == 0x85"))
        XCTAssertTrue(rendererText.contains("value == 0x8D"))
        XCTAssertTrue(rendererText.contains("value == 0x9B"))
        XCTAssertTrue(rendererText.contains("value == 0x9D"))
        XCTAssertTrue(rendererText.contains("value == 0x90"))
        XCTAssertTrue(rendererText.contains("value == 0x9F"))
        XCTAssertTrue(rendererText.contains("ambiguousWidthPolicy: TerminalOutputAmbiguousWidthPolicy = .narrow"))
        XCTAssertTrue(rendererText.contains("TerminalScreenBuffer(ambiguousWidthPolicy: ambiguousWidthPolicy)"))
    }

    func testTerminalRendererBehaviorTestsCoverScrollAndAlternateScreenParity() throws {
        let testsText = try Self.toolsTestSourceText(named: "TerminalOutputRendererTests.swift")

        XCTAssertTrue(testsText.contains("testScrollRegionLineFeedScrollsOnlyTheRegion"))
        XCTAssertTrue(testsText.contains("testC0VerticalTabAndFormFeedBehaveLikeLineFeeds"))
        XCTAssertTrue(testsText.contains("testStripsNonprintingC0AndDELControls"))
        XCTAssertTrue(testsText.contains("testC0VerticalTabScrollsOnlyTheCurrentRegion"))
        XCTAssertTrue(testsText.contains("testIndexAndNextLineEscapesMoveCursorDown"))
        XCTAssertTrue(testsText.contains("testC1IndexAndNextLineControlsMoveCursorDown"))
        XCTAssertTrue(testsText.contains("testIndexEscapeScrollsOnlyTheCurrentRegion"))
        XCTAssertTrue(testsText.contains("testReverseIndexScrollsDownInsideRegion"))
        XCTAssertTrue(testsText.contains("testC1ReverseIndexScrollsDownInsideRegion"))
        XCTAssertTrue(testsText.contains("testCSIExplicitScrollUpAndDownUseCurrentRegion"))
        XCTAssertTrue(testsText.contains("testC1CSISequencesShareTheNormalCSIParser"))
        XCTAssertTrue(testsText.contains("testRISResetClearsScreenCursorStyleAndModes"))
        XCTAssertTrue(testsText.contains("testRISResetDropsAlternateScreenSnapshot"))
        XCTAssertTrue(testsText.contains("testStripsTerminalStringControlPayloads"))
        XCTAssertTrue(testsText.contains("testHorizontalTabAdvancesToFixedTabStop"))
        XCTAssertTrue(testsText.contains("testCSIForwardAndBackwardTabMoveByFixedTabStops"))
        XCTAssertTrue(testsText.contains("testInsertAndDeleteLineOperateInsideTheVisibleBuffer"))
        XCTAssertTrue(testsText.contains("testInsertAndDeleteCharactersOperateAtCursor"))
        XCTAssertTrue(testsText.contains("testEraseCharactersBlanksCellsWithoutShiftingSuffix"))
        XCTAssertTrue(testsText.contains("testRepeatPreviousCharacterAppendsAtCursor"))
        XCTAssertTrue(testsText.contains("testInsertAndDeleteCharactersRespectWideCellBoundaries"))
        XCTAssertTrue(testsText.contains("testEraseCharactersRespectWideCellBoundaries"))
        XCTAssertTrue(testsText.contains("testRepeatPreviousCharacterUsesWideGlyphStart"))
        XCTAssertTrue(testsText.contains("testAlternateScreenExitPreservesLatestFrameForTranscriptScrollback"))
        XCTAssertTrue(testsText.contains("testWideCharactersAdvanceByTwoTerminalCells"))
        XCTAssertTrue(testsText.contains("testWideCharacterOverwriteClearsContinuationCell"))
        XCTAssertTrue(testsText.contains("testCombiningMarksDoNotAdvanceCursor"))
        XCTAssertTrue(testsText.contains("testZeroWidthJoinerEmojiClustersAdvanceAsOneWideGlyph"))
        XCTAssertTrue(testsText.contains("testEmojiPresentationSequencesAdvanceAsWideGlyphs"))
        XCTAssertTrue(testsText.contains("testAmbiguousWidthPolicyDefaultsToNarrowForTranscriptStability"))
        XCTAssertTrue(testsText.contains("testAmbiguousWidthPolicyCanRenderWideForLocaleSpecificTerminalFrames"))
        XCTAssertTrue(testsText.contains("testAmbiguousWidthPolicyAutomaticUsesWideForCJKLocales"))
        XCTAssertTrue(testsText.contains("testAmbiguousWidthPolicyAutomaticUsesProcessLocaleEnvironment"))
        XCTAssertTrue(testsText.contains("testAmbiguousWidthPolicyAutomaticEnvironmentOverrideWins"))
    }
}
