import XCTest

final class ParityWorkspaceModelThreadGateTests: QuillCodeParityTestCase {
    func testWorkspaceModelDelegatesProjectContextRefresh() throws {
        let modelText = try Self.appSourceText(named: "WorkspaceModel.swift")
        let composerText = try Self.appSourceText(named: "WorkspaceModelComposer.swift")
        let threadExtensionText = try Self.appSourceText(named: "WorkspaceModelThreads.swift")
        let worktreeExtensionText = try Self.appSourceText(named: "WorkspaceModelWorktrees.swift")
        let refresherText = try Self.appSourceText(named: "WorkspaceProjectContextRefresher.swift")
        let contextPreparerText = try Self.appSourceText(named: "WorkspaceThreadContextPreparer.swift")

        XCTAssertTrue(refresherText.contains("enum WorkspaceProjectContextRefresher"), "Project context refresh should have a focused owner.")
        XCTAssertTrue(refresherText.contains("refreshLocalProjectMetadata"), "Local project metadata refresh should be directly testable.")
        XCTAssertTrue(refresherText.contains("refreshRemoteProjectContext"), "Remote project metadata refresh should be directly testable.")
        XCTAssertTrue(refresherText.contains("syncThreadContext"), "Thread instruction and memory sync should be directly testable.")
        XCTAssertTrue(refresherText.contains("syncThreadMemories"), "Saved-memory refresh should be directly testable.")
        XCTAssertTrue(refresherText.contains("threadCreationContext"), "Thread creation context assembly should be directly testable.")
        XCTAssertTrue(refresherText.contains("worktreeOpenContext"), "Worktree open context assembly should be directly testable.")
        XCTAssertTrue(refresherText.contains("static func globalMemories"), "Global memory loading should be directly testable.")
        XCTAssertTrue(modelText.contains("WorkspaceProjectContextRefresher.refreshLocalProjectMetadata"), "WorkspaceModel should delegate local project metadata refresh.")
        XCTAssertTrue(modelText.contains("WorkspaceProjectContextRefresher.refreshRemoteProjectContext"), "WorkspaceModel should delegate remote project metadata refresh.")
        XCTAssertTrue(contextPreparerText.contains("WorkspaceProjectContextRefresher.syncThreadContext"), "Shared thread context preparation should delegate thread context sync.")
        XCTAssertTrue(composerText.contains("WorkspaceThreadContextPreparer.syncThreadContext"), "WorkspaceModel composer APIs should delegate thread context prep.")
        XCTAssertTrue(threadExtensionText.contains("WorkspaceProjectContextRefresher.threadCreationContext"), "WorkspaceModel thread APIs should delegate thread creation context assembly.")
        XCTAssertTrue(worktreeExtensionText.contains("WorkspaceProjectContextRefresher.worktreeOpenContext"), "WorkspaceModel worktree APIs should delegate worktree open context assembly.")
        XCTAssertFalse(modelText.contains("WorkspaceProjectContextRefresher.syncThreadContext"), "WorkspaceModel.swift should not own agent-send thread context sync.")
        XCTAssertFalse(composerText.contains("WorkspaceProjectContextRefresher.syncThreadContext"), "WorkspaceModel composer APIs should not directly own agent-send thread context sync.")
        XCTAssertFalse(modelText.contains("WorkspaceProjectContextRefresher.worktreeOpenContext"), "WorkspaceModel.swift should not own worktree open context assembly.")
        XCTAssertFalse(modelText.contains("WorkspaceProjectMetadataLoader.loadLocal(from: rootURL)"), "WorkspaceModel should not own refresh-time local project metadata loading.")
        XCTAssertFalse(modelText.contains("WorkspaceProjectMetadataLoader.loadRemote"), "WorkspaceModel should not own remote project metadata loading.")
        XCTAssertFalse(modelText.contains("WorkspaceMemoryEngine.loadGlobal(from:"), "WorkspaceModel should not own global memory loading.")
        XCTAssertFalse(modelText.contains("contextResolver.instructions(for:"), "WorkspaceModel should not read instruction snapshots directly from the context resolver.")
        XCTAssertFalse(modelText.contains("contextResolver.memoryNotes(for:"), "WorkspaceModel should not read memory snapshots directly from the context resolver.")
        XCTAssertFalse(modelText.contains("thread.instructions = contextResolver.instructions"), "WorkspaceModel should not directly sync thread instructions from the resolver.")
        XCTAssertFalse(modelText.contains("thread.memories = contextResolver.memoryNotes"), "WorkspaceModel should not directly sync thread memories from the resolver.")
    }

    func testWorkspaceModelDelegatesThreadSeedBuilding() throws {
        let modelText = try Self.appSourceText(named: "WorkspaceModel.swift")
        let seedBuilderText = try Self.appSourceText(named: "WorkspaceThreadSeedBuilder.swift")
        let creationText = try Self.appSourceText(named: "WorkspaceThreadCreationEngine.swift")
        let continuationText = try Self.appSourceText(named: "WorkspaceModelContextContinuations.swift")
        let threadExtensionText = try Self.appSourceText(named: "WorkspaceModelThreads.swift")
        let summaryGeneratorText = try Self.appSourceText(named: "WorkspaceContextSummaryGenerator.swift")
        let runtimeText = try Self.appSourceText(named: "RuntimeFactory.swift")

        XCTAssertTrue(seedBuilderText.contains("struct WorkspaceThreadSeedBuilder"), "Fork and compact seed construction should live in a focused builder.")
        XCTAssertTrue(seedBuilderText.contains("static func title(fromUserPrompt"), "Thread title seeding should be directly testable.")
        XCTAssertTrue(seedBuilderText.contains("static func forkSeedMessages"), "Fork seed construction should be directly testable.")
        XCTAssertTrue(seedBuilderText.contains("static func compactSeedMessages"), "Compact seed construction should be directly testable.")
        XCTAssertTrue(summaryGeneratorText.contains("protocol WorkspaceContextSummaryGenerating"), "Model-backed context summaries should live behind a focused summary generator protocol.")
        XCTAssertTrue(summaryGeneratorText.contains("struct LLMWorkspaceContextSummaryGenerator"), "Live context summaries should be implemented outside the workspace model.")
        XCTAssertTrue(runtimeText.contains("contextSummaryGenerator: LLMWorkspaceContextSummaryGenerator"), "TrustedRouter runtime should wire model-backed context summaries.")
        XCTAssertTrue(creationText.contains("WorkspaceThreadSeedBuilder.forkSeedMessages"), "Thread creation should delegate fork seeding.")
        XCTAssertTrue(creationText.contains("WorkspaceThreadSeedBuilder.compactSeedMessages"), "Thread creation should delegate context compaction seeding.")
        XCTAssertTrue(continuationText.contains("func startForkThread"), "Model-backed fork startup should live in the context continuation extension.")
        XCTAssertTrue(continuationText.contains("func compactContextWithConfiguredSummary"), "Model-backed compact execution should live in the context continuation extension.")
        XCTAssertTrue(continuationText.contains("WorkspaceContextSummaryTelemetryPlanner.continuationEvent"), "Continuation telemetry should stay beside model-backed context execution.")
        XCTAssertFalse(threadExtensionText.contains("contextSummaryGenerator.summary"), "Thread lifecycle APIs should not own model-backed context summary calls.")
        XCTAssertFalse(threadExtensionText.contains("recordContextSummarySourceNotice"), "Thread lifecycle APIs should not own context-summary notices.")
        XCTAssertFalse(modelText.contains("private static func forkSeedMessages"), "WorkspaceModel should not own fork seed construction.")
        XCTAssertFalse(modelText.contains("private static func compactSeedMessages"), "WorkspaceModel should not own compact seed construction.")
        XCTAssertFalse(modelText.contains("private static func compactSummaryMessage"), "WorkspaceModel should not own compact summary formatting.")
        XCTAssertFalse(modelText.contains("TrustedRouterLLMClient"), "WorkspaceModel should not know about the concrete TrustedRouter summarizer.")
    }

    func testWorkspaceModelDelegatesThreadCreationRecords() throws {
        let modelText = try Self.appSourceText(named: "WorkspaceModel.swift")
        let threadExtensionText = try Self.appSourceText(named: "WorkspaceModelThreads.swift")
        let threadSelectionText = try Self.appSourceText(named: "WorkspaceModelThreadSelection.swift")
        let creationText = try Self.appSourceText(named: "WorkspaceThreadCreationEngine.swift")

        XCTAssertTrue(threadExtensionText.contains("extension QuillCodeWorkspaceModel"), "Thread APIs should live in a focused WorkspaceModel extension.")
        XCTAssertTrue(threadSelectionText.contains("func insertCreatedThread"), "Created-thread insertion should live with thread selection and draft restoration.")
        XCTAssertTrue(threadSelectionText.contains("ComposerDraftStore.select"), "Thread selection should own composer draft switching.")
        XCTAssertTrue(creationText.contains("struct WorkspaceThreadCreationContext"), "New-thread context should live beside the focused creation engine.")
        XCTAssertTrue(creationText.contains("struct WorkspaceThreadCreationEngine"), "Thread record construction should live in a focused engine.")
        XCTAssertTrue(creationText.contains("static func newThread"), "New chat construction should be directly testable.")
        XCTAssertTrue(creationText.contains("static func forkThread"), "Fork thread construction should be directly testable.")
        XCTAssertTrue(creationText.contains("static func compactThread"), "Compact thread construction should be directly testable.")
        XCTAssertTrue(creationText.contains("static func duplicateThread"), "Duplicate thread construction should be directly testable.")
        XCTAssertTrue(threadExtensionText.contains("WorkspaceThreadCreationEngine.newThread"), "WorkspaceModel thread APIs should delegate new chat construction.")
        XCTAssertTrue(threadExtensionText.contains("WorkspaceThreadCreationEngine.forkThread"), "WorkspaceModel thread APIs should delegate fork construction.")
        XCTAssertTrue(threadExtensionText.contains("WorkspaceThreadCreationEngine.compactThread"), "WorkspaceModel thread APIs should delegate compact construction.")
        XCTAssertTrue(threadExtensionText.contains("WorkspaceThreadCreationEngine.duplicateThread"), "WorkspaceModel thread APIs should delegate duplicate construction.")
        XCTAssertFalse(modelText.contains("public func newChat"), "WorkspaceModel.swift should not own thread creation API bodies.")
        XCTAssertFalse(modelText.contains("public func forkFromLast"), "WorkspaceModel.swift should not own fork API bodies.")
        XCTAssertFalse(modelText.contains("public func compactContext"), "WorkspaceModel.swift should not own compact API bodies.")
        XCTAssertFalse(modelText.contains("public func duplicateThread"), "WorkspaceModel.swift should not own duplicate API bodies.")
        XCTAssertFalse(modelText.contains("title: \"Fork:"), "WorkspaceModel should not own fork title copy.")
        XCTAssertFalse(modelText.contains("title: \"Compact:"), "WorkspaceModel should not own compact title copy.")
        XCTAssertFalse(modelText.contains("title: \"Copy:"), "WorkspaceModel should not own duplicate title copy.")
    }

    func testWorkspaceModelDelegatesThreadLifecycleTransitions() throws {
        let modelText = try Self.appSourceText(named: "WorkspaceModel.swift")
        let threadExtensionText = try Self.appSourceText(named: "WorkspaceModelThreads.swift")
        let threadLifecycleText = try Self.appSourceText(named: "WorkspaceModelThreadLifecycleActions.swift")
        let threadSelectionText = try Self.appSourceText(named: "WorkspaceModelThreadSelection.swift")
        let threadMutationText = try Self.appSourceText(named: "WorkspaceModelThreadMutation.swift")
        let lifecycleText = try Self.appSourceText(named: "WorkspaceThreadLifecycleEngine.swift")
        let persistenceText = try Self.appSourceText(named: "WorkspaceThreadPersistence.swift")

        XCTAssertTrue(lifecycleText.contains("struct WorkspaceThreadLifecycleEngine"), "Thread lifecycle transitions should live in a focused engine.")
        XCTAssertTrue(persistenceText.contains("struct WorkspaceThreadPersistence"), "Thread persistence and timestamped mutation should live in a focused helper.")
        XCTAssertTrue(persistenceText.contains("func mutate("), "Timestamped thread mutation should be directly testable outside WorkspaceModel.")
        XCTAssertTrue(persistenceText.contains("func saveOrThrow"), "Throwing save semantics should stay isolated from direct JSONThreadStore calls.")
        XCTAssertTrue(lifecycleText.contains("static func renameThread"), "Thread rename mutation should be directly testable.")
        XCTAssertTrue(lifecycleText.contains("static func archiveThread"), "Thread archive fallback selection should be directly testable.")
        XCTAssertTrue(lifecycleText.contains("static func unarchiveThread"), "Thread unarchive mutation should be directly testable.")
        XCTAssertTrue(lifecycleText.contains("static func deleteThread"), "Thread delete fallback selection should be directly testable.")
        XCTAssertTrue(lifecycleText.contains("static func applyAgentRunThreadUpdate"), "Agent-run thread upsert and fallback selection should be directly testable.")
        XCTAssertTrue(threadLifecycleText.contains("WorkspaceThreadLifecycleEngine.renameThread"), "WorkspaceModel lifecycle actions should delegate thread rename mutation.")
        XCTAssertTrue(threadLifecycleText.contains("WorkspaceThreadLifecycleEngine.archiveThread"), "WorkspaceModel lifecycle actions should delegate thread archive mutation.")
        XCTAssertTrue(threadLifecycleText.contains("WorkspaceThreadLifecycleEngine.deleteThread"), "WorkspaceModel lifecycle actions should delegate thread delete mutation.")
        XCTAssertTrue(threadLifecycleText.contains("updateAndSaveThread"), "Shared rename/pin persistence should stay factored in lifecycle actions.")
        XCTAssertTrue(threadSelectionText.contains("func applyThreadDraftSelection"), "Draft selection should live in the focused selection extension.")
        XCTAssertTrue(threadSelectionText.contains("func selectThread"), "Thread selection should live in the focused selection extension.")
        XCTAssertTrue(threadMutationText.contains("WorkspaceThreadLifecycleEngine.applyAgentRunThreadUpdate"), "WorkspaceModel thread mutation extension should delegate agent-run thread upsert and fallback selection.")
        XCTAssertTrue(modelText.contains("WorkspaceThreadPersistence(store: threadStore)"), "WorkspaceModel should bridge its existing initializer to the thread persistence helper.")
        XCTAssertTrue(threadMutationText.contains("func mutateSelectedThread"), "Selected-thread mutation should live in the focused thread mutation extension.")
        XCTAssertTrue(threadMutationText.contains("func mutateThread"), "Timestamped thread mutation should live in the focused thread mutation extension.")
        XCTAssertTrue(threadMutationText.contains("func selectedSidebarThreadIDs"), "Sidebar selected-ID resolution should live in the focused thread mutation extension.")
        XCTAssertTrue(threadMutationText.contains("func validThreadIDs"), "Thread ID validity lookup should live in the focused thread mutation extension.")
        XCTAssertTrue(threadMutationText.contains("threadPersistence.mutate"), "WorkspaceModel thread mutation extension should delegate timestamped thread mutation.")
        XCTAssertFalse(modelText.contains("WorkspaceThreadLifecycleEngine.applyAgentRunThreadUpdate"), "WorkspaceModel.swift should not own agent-run thread replacement.")
        XCTAssertFalse(modelText.contains("func mutateSelectedThread"), "WorkspaceModel.swift should not own selected-thread mutation.")
        XCTAssertFalse(modelText.contains("func mutateThread"), "WorkspaceModel.swift should not own timestamped thread mutation.")
        XCTAssertFalse(modelText.contains("func selectedSidebarThreadIDs"), "WorkspaceModel.swift should not own sidebar selected-ID resolution.")
        XCTAssertFalse(modelText.contains("func validThreadIDs"), "WorkspaceModel.swift should not own thread ID validity lookup.")
        XCTAssertFalse(modelText.contains("threadPersistence.mutate"), "WorkspaceModel.swift should not own timestamped thread mutation.")
        XCTAssertFalse(modelText.contains("public func renameThread"), "WorkspaceModel.swift should not own thread rename API bodies.")
        XCTAssertFalse(modelText.contains("public func archiveThread"), "WorkspaceModel.swift should not own thread archive API bodies.")
        XCTAssertFalse(modelText.contains("public func unarchiveThread"), "WorkspaceModel.swift should not own thread unarchive API bodies.")
        XCTAssertFalse(modelText.contains("public func deleteThread"), "WorkspaceModel.swift should not own thread delete API bodies.")
        XCTAssertFalse(modelText.contains("thread.title = trimmed"), "WorkspaceModel should not own thread rename mutation.")
        XCTAssertFalse(modelText.contains("thread.isArchived = true"), "WorkspaceModel should not own thread archive mutation.")
        XCTAssertFalse(modelText.contains("thread.isArchived = false"), "WorkspaceModel should not own thread unarchive mutation.")
        XCTAssertFalse(modelText.contains("private func upsertThread"), "WorkspaceModel should not own generic thread upsert mutation.")
        XCTAssertFalse(modelText.contains("private func selectUpdatedThread"), "WorkspaceModel should not own agent-run fallback selection mutation.")
        XCTAssertFalse(modelText.contains("threadStore?.save"), "WorkspaceModel should not call JSONThreadStore save directly.")
        XCTAssertFalse(modelText.contains("threadStore?.delete"), "WorkspaceModel should not call JSONThreadStore delete directly.")
        XCTAssertFalse(threadExtensionText.contains("WorkspaceThreadLifecycleEngine.renameThread"), "Thread creation APIs should not own lifecycle mutation delegation.")
        XCTAssertFalse(threadExtensionText.contains("func applyThreadDraftSelection"), "Thread creation APIs should not own composer draft switching.")
    }

    func testWorkspaceModelDelegatesConfigurationTransitions() throws {
        let modelText = try Self.appSourceText(named: "WorkspaceModel.swift")
        let configurationExtensionText = try Self.appSourceText(named: "WorkspaceModelConfiguration.swift")
        let configurationText = try Self.appSourceText(named: "WorkspaceConfigurationEngine.swift")

        XCTAssertTrue(configurationText.contains("struct WorkspaceConfigurationEngine"), "Workspace configuration transitions should live in a focused engine.")
        XCTAssertTrue(configurationText.contains("static func setModel"), "Model selection should be directly testable.")
        XCTAssertTrue(configurationText.contains("static func setMode"), "Mode selection should be directly testable.")
        XCTAssertTrue(configurationText.contains("static func toggleFavorite"), "Favorite model mutation should be directly testable.")
        XCTAssertTrue(configurationText.contains("static func normalizedCatalog"), "Catalog replacement should be directly testable.")
        XCTAssertTrue(configurationText.contains("static func applySettings"), "Settings application should be directly testable.")
        XCTAssertTrue(configurationText.contains("static func syncThread"), "Selected-thread config syncing should be directly testable.")
        XCTAssertTrue(configurationExtensionText.contains("public func setMode"), "Mode selection should live in the focused configuration extension.")
        XCTAssertTrue(configurationExtensionText.contains("public func setModel"), "Model selection should live in the focused configuration extension.")
        XCTAssertTrue(configurationExtensionText.contains("public func toggleModelFavorite"), "Favorite model mutation should live in the focused configuration extension.")
        XCTAssertTrue(configurationExtensionText.contains("public func setModelCatalog"), "Catalog replacement should live in the focused configuration extension.")
        XCTAssertTrue(configurationExtensionText.contains("public func applySettings"), "Settings application should live in the focused configuration extension.")
        XCTAssertTrue(configurationExtensionText.contains("public func applyRuntime"), "Runtime application should live in the focused configuration extension.")
        XCTAssertTrue(configurationExtensionText.contains("public func setAgentStatus"), "Agent status overrides should live in the focused configuration extension.")
        XCTAssertTrue(configurationExtensionText.contains("WorkspaceConfigurationEngine.setModel"), "WorkspaceModelConfiguration should delegate model selection.")
        XCTAssertTrue(configurationExtensionText.contains("WorkspaceConfigurationEngine.setMode"), "WorkspaceModelConfiguration should delegate mode selection.")
        XCTAssertTrue(configurationExtensionText.contains("WorkspaceConfigurationEngine.toggleFavorite"), "WorkspaceModelConfiguration should delegate favorite mutation.")
        XCTAssertTrue(configurationExtensionText.contains("WorkspaceConfigurationEngine.normalizedCatalog"), "WorkspaceModelConfiguration should delegate catalog normalization.")
        XCTAssertTrue(configurationExtensionText.contains("WorkspaceConfigurationEngine.applySettings"), "WorkspaceModelConfiguration should delegate settings application.")
        XCTAssertFalse(modelText.contains("public func setMode"), "WorkspaceModel.swift should not own mode selection API bodies.")
        XCTAssertFalse(modelText.contains("public func setModel"), "WorkspaceModel.swift should not own model selection API bodies.")
        XCTAssertFalse(modelText.contains("public func toggleModelFavorite"), "WorkspaceModel.swift should not own favorite model API bodies.")
        XCTAssertFalse(modelText.contains("public func setModelCatalog"), "WorkspaceModel.swift should not own model catalog API bodies.")
        XCTAssertFalse(modelText.contains("public func applySettings"), "WorkspaceModel.swift should not own settings application API bodies.")
        XCTAssertFalse(modelText.contains("public func applyRuntime"), "WorkspaceModel.swift should not own runtime application API bodies.")
        XCTAssertFalse(modelText.contains("public func setAgentStatus"), "WorkspaceModel.swift should not own agent status override API bodies.")
        XCTAssertFalse(modelText.contains("TrustedRouterDefaults.normalizedDefaultModelID(model)"), "WorkspaceModel should not own model ID normalization.")
        XCTAssertFalse(modelText.contains("root.config.favoriteModels.append"), "WorkspaceModel should not mutate favorite-model arrays directly.")
        XCTAssertFalse(modelText.contains("TrustedRouterDefaults.normalizedModelCatalog(models)"), "WorkspaceModel should not own catalog normalization.")
        XCTAssertFalse(modelText.contains("root.trustedRouterAPIKeyConfigured = trustedRouterAPIKeyConfigured"), "WorkspaceModel should not own settings application details.")
    }

    func testWorkspaceConfigurationIntegrationTestsOwnModelConfigurationFlows() throws {
        let modelTests = try Self.appTestSourceText(named: "WorkspaceModelTests.swift")
        let configurationIntegrationTests = try Self.appTestSourceText(named: "WorkspaceConfigurationIntegrationTests.swift")

        XCTAssertTrue(configurationIntegrationTests.contains("testModeAndModelUpdateSelectedThreadAndTopBar"), "Mode/model top-bar integration should live in focused configuration integration tests.")
        XCTAssertTrue(configurationIntegrationTests.contains("testToggleModelFavoriteUpdatesConfigAndSurface"), "Favorite model config/surface integration should live in focused configuration integration tests.")
        XCTAssertTrue(configurationIntegrationTests.contains("testApplySettingsUpdatesConfigThreadAndSettingsSurface"), "Settings config/thread/surface integration should live in focused configuration integration tests.")
        XCTAssertTrue(configurationIntegrationTests.contains("testBootstrapLoadsConfigAndPersistedThreads"), "Bootstrap config/thread/project/automation persistence integration should live in focused configuration integration tests.")
        XCTAssertTrue(configurationIntegrationTests.contains("testBootstrapPersistsAndClearsTrustedRouterAPIKey"), "TrustedRouter API key persistence integration should live in focused configuration integration tests.")

        XCTAssertFalse(modelTests.contains("testModeAndModelUpdateSelectedThreadAndTopBar"), "WorkspaceModelTests should not own mode/model surface integration flows.")
        XCTAssertFalse(modelTests.contains("testToggleModelFavoriteUpdatesConfigAndSurface"), "WorkspaceModelTests should not own favorite model config/surface integration flows.")
        XCTAssertFalse(modelTests.contains("testApplySettingsUpdatesConfigThreadAndSettingsSurface"), "WorkspaceModelTests should not own settings config/thread/surface integration flows.")
        XCTAssertFalse(modelTests.contains("testBootstrapLoadsConfigAndPersistedThreads"), "WorkspaceModelTests should not own bootstrap config/thread/project/automation persistence integration.")
        XCTAssertFalse(modelTests.contains("testBootstrapPersistsAndClearsTrustedRouterAPIKey"), "WorkspaceModelTests should not own TrustedRouter API key persistence integration.")
    }

}
