import XCTest

final class ParityDesktopBrowserAdapterGateTests: QuillCodeParityTestCase {
    func testDesktopBrowserLiveDOMCaptureUsesFocusedAdapter() throws {
        let desktopText = try Self.desktopSourceText()
        let controllerText = try Self.desktopControllerSourceText()
        let browserCoordinatorText = try Self.desktopSourceText(named: "QuillCodeDesktopBrowserCoordinator.swift")
        let capturerText = try Self.desktopSourceText(named: "DesktopBrowserLiveDOMCapturer.swift")
        let extractorText = try Self.desktopSourceText(named: "DesktopBrowserLiveDOMSnapshotExtractor.swift")
        let chromiumCapturerText = try Self.desktopSourceText(named: "ChromiumBrowserLiveDOMCapturer.swift")
        let chromiumCapturerTests = try Self.desktopTestSourceText(named: "ChromiumBrowserLiveDOMCapturerTests.swift")

        Self.assertSource(desktopText, contains: "QuillCodeDesktopBrowserCoordinator")
        Self.assertSource(desktopText, contains: "DesktopBrowserLiveDOMCapturer")
        Self.assertSource(capturerText, contains: "BrowserLiveDOMCapturing")
        Self.assertSource(capturerText, contains: "WKWebView")
        Self.assertSource(capturerText, contains: "DesktopBrowserLiveDOMSnapshotExtractor.snapshot")
        Self.assertSource(extractorText, contains: "evaluateJavaScript")
        Self.assertSource(extractorText, contains: "BrowserLiveDOMSnapshot")
        Self.assertSource(capturerText, contains: "enum DesktopBrowserLiveDOMProfile")
        Self.assertSource(capturerText, contains: "case persistent")
        Self.assertSource(capturerText, contains: "case ephemeral")
        Self.assertSource(capturerText, contains: "profile: DesktopBrowserLiveDOMProfile = .persistent")
        Self.assertSource(capturerText, contains: "WKWebsiteDataStore")
        Self.assertSource(capturerText, contains: "return .default()")
        Self.assertSource(capturerText, contains: "typealias DesktopBrowserLiveDOMCapturer = ChromiumBrowserLiveDOMCapturer")
        Self.assertSource(chromiumCapturerText, contains: "final class ChromiumBrowserLiveDOMCapturer")
        Self.assertSource(chromiumCapturerText, contains: "BrowserProcessExecutableLocator")
        Self.assertSource(chromiumCapturerText, contains: #""chromium-browser""#)
        Self.assertSource(chromiumCapturerText, contains: #""google-chrome-stable""#)
        Self.assertSource(chromiumCapturerText, contains: #""--headless=new""#)
        Self.assertSource(chromiumCapturerText, contains: #""--dump-dom""#)
        Self.assertSource(chromiumCapturerText, contains: "RenderedBrowserHTMLSnapshotParser.snapshot")
        Self.assertSource(chromiumCapturerTests, contains: "testCapturerBuildsHeadlessInvocationAndParsesRenderedDOM")
        Self.assertSource(chromiumCapturerTests, contains: "testCapturerReportsNoRenderedSessionWhenBrowserIsMissing")
        Self.assertSource(controllerText, contains: "browserLiveDOMCapturer")
        Self.assertSource(controllerText, contains: "browserCoordinator.openPreview")
        XCTAssertTrue(
            browserCoordinatorText.contains("refreshRenderedBrowserSnapshot(capturer: liveDOMCapturer)"),
            "Desktop browser preview coordinator should upgrade fetched snapshots with rendered live DOM when available."
        )
        Self.assertSource(controllerText, excludes: "WKWebView")
        Self.assertSource(controllerText, excludes: "ChromiumBrowserLiveDOMCapturer")
        Self.assertSource(controllerText, excludes: "--dump-dom")
        Self.assertSource(controllerText, excludes: "evaluateJavaScript")
        Self.assertSource(controllerText, excludes: "import WebKit")
        Self.assertSource(controllerText, excludes: "document.body")
    }

    func testDesktopBrowserVisibleSessionUsesFocusedAdapter() throws {
        let desktopText = try Self.desktopSourceText()
        let controllerText = try Self.desktopControllerSourceText()
        let visibleToolExecutorText = try Self.desktopSourceText(named: "QuillCodeDesktopVisibleBrowserToolExecutor.swift")
        let browserCoordinatorText = try Self.desktopSourceText(named: "QuillCodeDesktopBrowserCoordinator.swift")
        let appText = try Self.desktopSourceText(named: "QuillCodeDesktopApp.swift")
        let presenterText = try Self.desktopSourceText(named: "DesktopBrowserSessionPresenter.swift")
        let extractorText = try Self.desktopSourceText(named: "DesktopBrowserLiveDOMSnapshotExtractor.swift")
        let browserPaneText = try Self.appSourceText(named: "QuillCodeBrowserPaneView.swift")
        let browserControlsText = try Self.appSourceText(named: "QuillCodeBrowserPaneControls.swift")
        let commandCatalogText = try Self.appSourceText(named: "WorkspaceCommandStaticCatalog.swift")
        let viewCommandPlannerText = try Self.appSourceText(named: "QuillCodeWorkspaceViewCommandPlanner.swift")

        Self.assertSource(desktopText, contains: "DesktopBrowserSessionPresenter")
        Self.assertSource(presenterText, contains: "protocol DesktopBrowserSessionPresenting")
        Self.assertSource(presenterText, contains: "WKWebView")
        Self.assertSource(presenterText, contains: "configuration.websiteDataStore = .default()")
        Self.assertSource(presenterText, contains: "loadFileURL")
        Self.assertSource(presenterText, contains: "private var session: DesktopBrowserSessionWindowController?")
        Self.assertSource(presenterText, contains: "presentSession(_ snapshot: BrowserSessionSyncSnapshot)")
        Self.assertSource(presenterText, contains: "syncSession(_ snapshot: BrowserSessionSyncSnapshot)")
        Self.assertSource(presenterText, contains: "goBackSession(fallback snapshot: BrowserSessionSyncSnapshot)")
        Self.assertSource(presenterText, contains: "goForwardSession(fallback snapshot: BrowserSessionSyncSnapshot)")
        Self.assertSource(presenterText, contains: "evaluateJavaScriptInSelectedTab(_ source: String)")
        Self.assertSource(presenterText, contains: "captureLiveDOMSnapshotInSelectedTab()")
        Self.assertSource(presenterText, contains: "clickInSelectedTab(selector: String)")
        Self.assertSource(presenterText, contains: "typeInSelectedTab(selector: String, text: String, submit: Bool)")
        Self.assertSource(presenterText, contains: "reloadSession()")
        Self.assertSource(presenterText, contains: "session?.goBackSelectedTab(fallback: snapshot)")
        Self.assertSource(presenterText, contains: "session?.goForwardSelectedTab(fallback: snapshot)")
        Self.assertSource(presenterText, contains: "session.evaluateJavaScriptInSelectedTab(source)")
        Self.assertSource(presenterText, contains: "session.captureLiveDOMSnapshotInSelectedTab()")
        Self.assertSource(presenterText, contains: "session.clickInSelectedTab(selector: selector)")
        Self.assertSource(presenterText, contains: "session.typeInSelectedTab(selector: selector, text: text, submit: submit)")
        Self.assertSource(presenterText, contains: "session?.reloadSelectedTab()")
        Self.assertSource(presenterText, contains: "tab.webView.goBack()")
        Self.assertSource(presenterText, contains: "tab.webView.goForward()")
        Self.assertSource(presenterText, contains: "tab.webView.evaluateJavaScript(trimmedSource)")
        Self.assertSource(presenterText, contains: "document.querySelector(selector)")
        Self.assertSource(presenterText, contains: "element.click()")
        Self.assertSource(presenterText, contains: "element.dispatchEvent(new InputEvent")
        Self.assertSource(presenterText, contains: "JSONEncoder().encode(value)")
        Self.assertSource(presenterText, contains: "DesktopBrowserLiveDOMSnapshotExtractor.snapshot")
        Self.assertSource(presenterText, contains: "tab.webView.reload()")
        Self.assertSource(presenterText, contains: "session.sync(snapshot)")
        Self.assertSource(presenterText, contains: "emitRenderedSessionUpdate")
        Self.assertSource(presenterText, contains: "liveDOMSnapshot: liveDOMSnapshots[id]")
        Self.assertSource(extractorText, contains: "DesktopBrowserLiveDOMSnapshotExtractor")
        Self.assertSource(presenterText, contains: "NSTabView")
        Self.assertSource(presenterText, contains: "func present()")
        Self.assertSource(presenterText, excludes: "sessions: [ObjectIdentifier")
        Self.assertSource(presenterText, excludes: "func openSession(url: URL)")
        Self.assertSource(controllerText, contains: "browserSessionPresenter")
        Self.assertSource(controllerText, contains: "browserCoordinator.openSession")
        Self.assertSource(controllerText, contains: "browserCoordinator.syncOpenSession")
        Self.assertSource(controllerText, contains: "browserCoordinator.goBackOpenSession")
        Self.assertSource(controllerText, contains: "browserCoordinator.goForwardOpenSession")
        Self.assertSource(controllerText, contains: "browserCoordinator.reloadOpenSession")
        Self.assertSource(browserCoordinatorText, contains: "func evaluateJavaScriptInOpenSession")
        Self.assertSource(browserCoordinatorText, contains: "WorkspaceBrowserLocationResolver(workspaceRoot: root).resolve")
        Self.assertSource(browserCoordinatorText, contains: "BrowserSessionSyncSnapshot(browser: model.browser)")
        Self.assertSource(browserCoordinatorText, contains: "sessionPresenter.goBackSession(fallback: snapshot)")
        Self.assertSource(browserCoordinatorText, contains: "sessionPresenter.goForwardSession(fallback: snapshot)")
        Self.assertSource(browserCoordinatorText, contains: "sessionPresenter.evaluateJavaScriptInSelectedTab(source)")
        Self.assertSource(browserCoordinatorText, contains: "func captureLiveDOMSnapshotInOpenSession")
        Self.assertSource(browserCoordinatorText, contains: "sessionPresenter.captureLiveDOMSnapshotInSelectedTab()")
        Self.assertSource(browserCoordinatorText, contains: "func clickInOpenSession(selector: String)")
        Self.assertSource(browserCoordinatorText, contains: "sessionPresenter.clickInSelectedTab(selector: selector)")
        Self.assertSource(browserCoordinatorText, contains: "func typeInOpenSession(selector: String, text: String, submit: Bool)")
        Self.assertSource(browserCoordinatorText, contains: "sessionPresenter.typeInSelectedTab(selector: selector, text: text, submit: submit)")
        Self.assertSource(browserCoordinatorText, contains: "func inspectLiveDOMSnapshotInOpenSession")
        Self.assertSource(controllerText, contains: "model.visibleBrowserToolOverride")
        Self.assertSource(controllerText, contains: "QuillCodeDesktopVisibleBrowserToolExecutor.execute")
        Self.assertSource(visibleToolExecutorText, contains: "ToolDefinition.browserInspect.name")
        Self.assertSource(visibleToolExecutorText, contains: "ToolDefinition.browserClick.name")
        Self.assertSource(visibleToolExecutorText, contains: "ToolDefinition.browserType.name")
        Self.assertSource(visibleToolExecutorText, contains: "browserCoordinator.inspectLiveDOMSnapshotInOpenSession()")
        Self.assertSource(visibleToolExecutorText, contains: "browserCoordinator.clickInOpenSession(selector: selector)")
        Self.assertSource(visibleToolExecutorText, contains: "browserCoordinator.typeInOpenSession(")
        Self.assertSource(visibleToolExecutorText, contains: "BrowserActionToolOutput")
        Self.assertSource(browserCoordinatorText, contains: "sessionPresenter.reloadSession()")
        Self.assertSource(controllerText, contains: "func openBrowserSession()")
        Self.assertSource(appText, contains: "onOpenBrowserSession: controller.openBrowserSession")
        Self.assertSource(browserPaneText, contains: "var onOpenSession: (() -> Void)?")
        XCTAssertTrue(browserControlsText.contains(#"Button("Session", action: onOpenSession)"#), "Browser pane should expose a compact visible session action when available.")
        XCTAssertTrue(commandCatalogText.contains(#""open-browser-session""#), "Command palette should expose visible browser sessions.")
        Self.assertSource(commandCatalogText, contains: "browserCanOpenSession")
        XCTAssertTrue(viewCommandPlannerText.contains(#"case "open-browser-session":"#), "Shared command routing should present visible sessions without falling through to text insertion.")
        Self.assertSource(controllerText, excludes: "WKWebView")
        Self.assertSource(controllerText, excludes: "import WebKit")
        Self.assertSource(controllerText, excludes: "document.querySelector")
        Self.assertSource(controllerText, excludes: "BrowserActionToolOutput")
    }

}
