import XCTest

final class ParityDesktopControllerGateTests: QuillCodeParityTestCase {
    func testDesktopControllerDelegatesSettingsPersistenceAndSystemSettings() throws {
        let text = try Self.desktopSourceText()
        let controllerText = try Self.desktopSourceText(named: "QuillCodeDesktopController.swift")
        let settingsCoordinatorText = try Self.desktopSourceText(named: "QuillCodeDesktopSettingsCoordinator.swift")
        let computerUseCoordinatorText = try Self.desktopSourceText(named: "QuillCodeDesktopComputerUseCoordinator.swift")

        Self.assertSource(text, contains: "QuillCodeDesktopSettingsCoordinator")
        Self.assertSource(text, contains: "MacSystemSettingsOpener")
        Self.assertSource(text, contains: "QuillCodeDesktopComputerUseCoordinator")
        Self.assertSource(controllerText, contains: "settingsCoordinator.setMode")
        Self.assertSource(controllerText, contains: "settingsCoordinator.setModel")
        Self.assertSource(controllerText, contains: "settingsCoordinator.toggleModelFavorite")
        Self.assertSource(controllerText, contains: "settingsCoordinator.refreshModelCatalog")
        Self.assertSource(controllerText, contains: "settingsCoordinator.saveSettings")
        Self.assertSource(settingsCoordinatorText, contains: "model.setMode")
        Self.assertSource(settingsCoordinatorText, contains: "model.setModel")
        Self.assertSource(settingsCoordinatorText, contains: "model.toggleModelFavorite")
        Self.assertSource(settingsCoordinatorText, contains: "fetchModelCatalog")
        Self.assertSource(settingsCoordinatorText, contains: "model.setModelCatalog")
        Self.assertSource(settingsCoordinatorText, contains: "model.applySettings")
        Self.assertSource(settingsCoordinatorText, contains: "model.applyRuntime")
        Self.assertSource(controllerText, contains: "computerUseCoordinator.openSystemSettings")
        Self.assertSource(controllerText, contains: "computerUseCoordinator.refreshStatus")
        Self.assertSource(computerUseCoordinatorText, contains: "ComputerUseBackendFactory.platformDefault")
        Self.assertSource(computerUseCoordinatorText, contains: "model.setComputerUseBackend")
        Self.assertSource(computerUseCoordinatorText, contains: "model.setComputerUseStatus")
        Self.assertSource(computerUseCoordinatorText, contains: "systemSettingsOpener.open")
        Self.assertSource(controllerText, excludes: "model.setMode(")
        Self.assertSource(controllerText, excludes: "model.setModel(")
        Self.assertSource(controllerText, excludes: "model.toggleModelFavorite")
        Self.assertSource(controllerText, excludes: "bootstrap.fetchModelCatalog")
        Self.assertSource(controllerText, excludes: "model.setModelCatalog")
        Self.assertSource(controllerText, excludes: "model.applySettings")
        Self.assertSource(controllerText, excludes: "model.applyRuntime")
        Self.assertSource(controllerText, excludes: "saveTrustedRouterAPIKey")
        Self.assertSource(controllerText, excludes: "clearTrustedRouterAPIKey")
        Self.assertSource(controllerText, excludes: "trustedRouterAccount = nil")
        Self.assertSource(controllerText, excludes: "MacComputerUseBackend")
        Self.assertSource(controllerText, excludes: "model.setComputerUseBackend")
        Self.assertSource(controllerText, excludes: "model.setComputerUseStatus")
        Self.assertSource(controllerText, excludes: "systemSettingsOpener.open")
        Self.assertSource(controllerText, excludes: "NSWorkspace.shared.open")
        Self.assertSource(controllerText, excludes: "x-apple.systempreferences")
        Self.assertSource(controllerText, excludes: "Privacy_ScreenCapture")
        Self.assertSource(controllerText, excludes: "Privacy_Accessibility")
        Self.assertSource(computerUseCoordinatorText, excludes: "MacComputerUseBackend")
    }

    func testDesktopControllerDelegatesTranscriptCopyFeedback() throws {
        let text = try Self.desktopSourceText()
        let controllerText = try Self.desktopSourceText(named: "QuillCodeDesktopController.swift")
        let copyText = try Self.desktopSourceText(named: "QuillCodeDesktopCopyCoordinator.swift")

        Self.assertSource(text, contains: "QuillCodeDesktopCopyCoordinator")
        Self.assertSource(copyText, contains: "protocol QuillCodePasteboardWriting")
        Self.assertSource(copyText, contains: "struct MacPasteboardWriter")
        Self.assertSource(copyText, contains: "struct QuillCodeDesktopCopyFeedback")
        Self.assertSource(copyText, contains: "defaultFeedbackDurationNanoseconds")
        Self.assertSource(controllerText, contains: "copyCoordinator.copyTranscriptItem")
        Self.assertSource(controllerText, contains: "feedback.clearAfterNanoseconds")
        Self.assertSource(controllerText, excludes: "NSPasteboard")
        Self.assertSource(controllerText, excludes: "clearContents()")
        Self.assertSource(controllerText, excludes: "setString(text, forType: .string)")
        Self.assertSource(controllerText, excludes: "1_500_000_000")
        Self.assertSource(controllerText, excludes: "import AppKit")
    }

    func testDesktopControllerDelegatesProjectImportResolution() throws {
        let text = try Self.desktopSourceText()
        let controllerText = try Self.desktopSourceText(named: "QuillCodeDesktopController.swift")
        let importText = try Self.desktopSourceText(named: "QuillCodeDesktopProjectImportCoordinator.swift")

        Self.assertSource(text, contains: "QuillCodeDesktopProjectImportCoordinator")
        Self.assertSource(importText, contains: "struct QuillCodeDesktopProjectImportSelection")
        Self.assertSource(importText, contains: "func selectedProject(from result:")
        Self.assertSource(importText, contains: "fileExists(atPath: url.path, isDirectory:")
        Self.assertSource(controllerText, contains: "projectImportCoordinator.selectedProject")
        Self.assertSource(controllerText, excludes: "guard case let .success(urls)")
        Self.assertSource(controllerText, excludes: "urls.first")
        Self.assertSource(controllerText, excludes: "fileExists(atPath:")
    }

    func testDesktopControllerDelegatesPaneMutations() throws {
        let text = try Self.desktopSourceText()
        let controllerText = try Self.desktopSourceText(named: "QuillCodeDesktopController.swift")
        let paneCoordinatorText = try Self.desktopSourceText(named: "QuillCodeDesktopPaneCoordinator.swift")

        Self.assertSource(text, contains: "QuillCodeDesktopPaneCoordinator")
        Self.assertSource(controllerText, contains: "paneCoordinator.toggleTerminal")
        Self.assertSource(controllerText, contains: "paneCoordinator.toggleBrowser")
        Self.assertSource(controllerText, contains: "paneCoordinator.toggleExtensions")
        Self.assertSource(controllerText, contains: "paneCoordinator.toggleMemories")
        Self.assertSource(controllerText, contains: "paneCoordinator.toggleActivity")
        Self.assertSource(controllerText, contains: "paneCoordinator.toggleAutomations")
        Self.assertSource(controllerText, contains: "paneCoordinator.addBrowserComment")
        Self.assertSource(paneCoordinatorText, contains: "model.toggleTerminal()")
        Self.assertSource(paneCoordinatorText, contains: "model.toggleBrowser()")
        Self.assertSource(paneCoordinatorText, contains: "model.toggleExtensions()")
        Self.assertSource(paneCoordinatorText, contains: "model.toggleMemories()")
        Self.assertSource(paneCoordinatorText, contains: "model.toggleActivity()")
        Self.assertSource(paneCoordinatorText, contains: "model.toggleAutomations()")
        Self.assertSource(paneCoordinatorText, contains: "model.addBrowserComment(comment)")
        Self.assertSource(controllerText, excludes: "model.toggleTerminal()")
        Self.assertSource(controllerText, excludes: "model.toggleBrowser()")
        Self.assertSource(controllerText, excludes: "model.toggleExtensions()")
        Self.assertSource(controllerText, excludes: "model.toggleMemories()")
        Self.assertSource(controllerText, excludes: "model.toggleActivity()")
        Self.assertSource(controllerText, excludes: "model.toggleAutomations()")
        Self.assertSource(controllerText, excludes: "model.addBrowserComment(comment)")
    }

    func testDesktopControllerDelegatesWorkspaceActionMutations() throws {
        let text = try Self.desktopSourceText()
        let controllerText = try Self.desktopSourceText(named: "QuillCodeDesktopController.swift")
        let actionCoordinatorText = try Self.desktopSourceText(named: "QuillCodeDesktopWorkspaceActionCoordinator.swift")

        Self.assertSource(text, contains: "QuillCodeDesktopWorkspaceActionCoordinator")
        Self.assertSource(controllerText, contains: "workspaceActionCoordinator.runToolCardAction")
        Self.assertSource(controllerText, contains: "workspaceActionCoordinator.runReviewAction")
        Self.assertSource(controllerText, contains: "workspaceActionCoordinator.addReviewComment")
        Self.assertSource(controllerText, contains: "workspaceActionCoordinator.setMessageFeedback")
        Self.assertSource(controllerText, contains: "workspaceActionCoordinator.runWorkspaceCommand")
        Self.assertSource(actionCoordinatorText, contains: "model.runToolCardAction")
        Self.assertSource(actionCoordinatorText, contains: "model.runReviewAction")
        Self.assertSource(actionCoordinatorText, contains: "model.addReviewComment")
        Self.assertSource(actionCoordinatorText, contains: "model.setMessageFeedback")
        Self.assertSource(actionCoordinatorText, contains: "model.runWorkspaceCommand")
        Self.assertSource(actionCoordinatorText, contains: "model.activeWorkspaceRoot ?? fallback")
        Self.assertSource(controllerText, excludes: "model.runToolCardAction")
        Self.assertSource(controllerText, excludes: "model.runReviewAction")
        Self.assertSource(controllerText, excludes: "model.addReviewComment")
        Self.assertSource(controllerText, excludes: "model.setMessageFeedback")
        Self.assertSource(controllerText, excludes: "model.runWorkspaceCommand")
    }

    func testDesktopControllerDelegatesModelStateSynchronization() throws {
        let text = try Self.desktopSourceText()
        let controllerText = try Self.desktopSourceText(named: "QuillCodeDesktopController.swift")
        let stateCoordinatorText = try Self.desktopSourceText(named: "QuillCodeDesktopModelStateCoordinator.swift")

        Self.assertSource(text, contains: "QuillCodeDesktopModelStateCoordinator")
        Self.assertSource(controllerText, contains: "modelStateCoordinator.ensureDefaultProject")
        Self.assertSource(controllerText, contains: "modelStateCoordinator.initialState")
        Self.assertSource(controllerText, contains: "modelStateCoordinator.refreshState")
        Self.assertSource(controllerText, contains: "modelStateCoordinator.syncComposerDraft")
        Self.assertSource(stateCoordinatorText, contains: "model.root.projects.isEmpty")
        Self.assertSource(stateCoordinatorText, contains: "model.addProject(path: workspaceRoot)")
        Self.assertSource(stateCoordinatorText, contains: "model.surface()")
        Self.assertSource(stateCoordinatorText, contains: "model.composer.draft")
        Self.assertSource(stateCoordinatorText, contains: "model.terminal.draft")
        Self.assertSource(stateCoordinatorText, contains: "model.browser.addressDraft")
        Self.assertSource(controllerText, excludes: "model.root.projects.isEmpty")
        Self.assertSource(controllerText, excludes: "model.addProject(path: workspaceRoot)")
        Self.assertSource(controllerText, excludes: "model.surface()")
        Self.assertSource(controllerText, excludes: "model.composer.draft")
        Self.assertSource(controllerText, excludes: "model.terminal.draft")
        Self.assertSource(controllerText, excludes: "model.browser.addressDraft")
    }

    func testDesktopControllerDelegatesNavigationMutations() throws {
        let text = try Self.desktopSourceText()
        let controllerText = try Self.desktopSourceText(named: "QuillCodeDesktopController.swift")
        let navigationText = try Self.desktopSourceText(named: "QuillCodeDesktopNavigationCoordinator.swift")

        Self.assertSource(text, contains: "QuillCodeDesktopNavigationCoordinator")
        Self.assertSource(controllerText, contains: "navigationCoordinator.newChat")
        Self.assertSource(controllerText, contains: "navigationCoordinator.selectThread")
        Self.assertSource(controllerText, contains: "navigationCoordinator.runThreadAction")
        Self.assertSource(controllerText, contains: "navigationCoordinator.renameThread")
        Self.assertSource(controllerText, contains: "navigationCoordinator.selectProject")
        Self.assertSource(controllerText, contains: "navigationCoordinator.runProjectAction")
        Self.assertSource(controllerText, contains: "navigationCoordinator.renameProject")
        Self.assertSource(controllerText, contains: "navigationCoordinator.addProject")
        Self.assertSource(navigationText, contains: "model.newChat()")
        Self.assertSource(navigationText, contains: "model.selectThread(id)")
        Self.assertSource(navigationText, contains: "WorkspaceSidebarRowMutationExecutor.execute(mutation, model: model)")
        Self.assertSource(navigationText, contains: "model.renameThread(id, to: title)")
        Self.assertSource(navigationText, contains: "model.selectProject(id)")
        Self.assertSource(navigationText, contains: "model.renameProject(id, to: name)")
        Self.assertSource(navigationText, contains: "model.addProject(path: url)")
        Self.assertSource(controllerText, excludes: "_ = model.newChat()")
        Self.assertSource(controllerText, excludes: "model.selectThread(id)")
        Self.assertSource(controllerText, excludes: "WorkspaceSidebarRowMutationExecutor.execute(mutation, model: model)")
        Self.assertSource(controllerText, excludes: "model.renameThread(id, to: title)")
        Self.assertSource(controllerText, excludes: "model.selectProject(id)")
        Self.assertSource(controllerText, excludes: "model.renameProject(id, to: name)")
        Self.assertSource(controllerText, excludes: "model.addProject(path: url)")
    }

    func testDesktopControllerDelegatesWorktreeActions() throws {
        let text = try Self.desktopSourceText()
        let controllerText = try Self.desktopSourceText(named: "QuillCodeDesktopController.swift")
        let worktreeText = try Self.desktopSourceText(named: "QuillCodeDesktopWorktreeCoordinator.swift")

        Self.assertSource(text, contains: "QuillCodeDesktopWorktreeCoordinator")
        Self.assertSource(controllerText, contains: "worktreeCoordinator.createWorktree")
        Self.assertSource(controllerText, contains: "worktreeCoordinator.worktreeChoiceLoad")
        Self.assertSource(controllerText, contains: "worktreeCoordinator.worktreePrunePreview")
        Self.assertSource(controllerText, contains: "worktreeCoordinator.openWorktree")
        Self.assertSource(controllerText, contains: "worktreeCoordinator.removeWorktree")
        Self.assertSource(controllerText, contains: "worktreeCoordinator.pruneWorktrees")
        Self.assertSource(worktreeText, contains: "model.createWorktree(request, workspaceRoot:")
        Self.assertSource(worktreeText, contains: "model.worktreeChoiceLoadRequest(")
        Self.assertSource(worktreeText, contains: "model.worktreePrunePreviewLoadRequest(")
        Self.assertSource(worktreeText, contains: "model.openWorktree(request, workspaceRoot:")
        Self.assertSource(worktreeText, contains: "model.removeWorktree(request, workspaceRoot:")
        Self.assertSource(worktreeText, contains: "model.pruneWorktrees(request, workspaceRoot:")
        Self.assertSource(worktreeText, contains: "Task.detached(priority: .userInitiated)")
        Self.assertSource(worktreeText, contains: "model.activeWorkspaceRoot ?? workspaceRoot")
        Self.assertSource(controllerText, excludes: "model.createWorktree(request, workspaceRoot:")
        Self.assertSource(controllerText, excludes: "model.worktreeChoiceLoadRequest(workspaceRoot:")
        Self.assertSource(controllerText, excludes: "model.worktreePrunePreviewLoadRequest(workspaceRoot:")
        Self.assertSource(controllerText, excludes: "model.openWorktree(request, workspaceRoot:")
        Self.assertSource(controllerText, excludes: "model.removeWorktree(request, workspaceRoot:")
        Self.assertSource(controllerText, excludes: "model.pruneWorktrees(request, workspaceRoot:")
        Self.assertSource(controllerText, excludes: "Task.detached(priority: .userInitiated)")
    }

    func testDesktopControllerDelegatesCommandPlanning() throws {
        let text = try Self.desktopSourceText()
        let controllerText = try Self.desktopSourceText(named: "QuillCodeDesktopController.swift")
        let plannerText = try Self.desktopSourceText(named: "QuillCodeDesktopCommandPlanner.swift")
        let coordinatorText = try Self.desktopSourceText(named: "QuillCodeDesktopCommandCoordinator.swift")

        Self.assertSource(text, contains: "QuillCodeDesktopCommandPlanner")
        Self.assertSource(text, contains: "QuillCodeDesktopCommandCoordinator")
        Self.assertSource(plannerText, contains: "enum QuillCodeDesktopCommandAction")
        Self.assertSource(plannerText, contains: "static func action(for command: WorkspaceCommandSurface)")
        Self.assertSource(coordinatorText, contains: "protocol QuillCodeDesktopCommandPerforming")
        Self.assertSource(coordinatorText, contains: "switch action")
        Self.assertSource(plannerText, contains: "case \"computer-use-open-screen-recording\"")
        Self.assertSource(plannerText, contains: "case \"open-browser-session\"")
        Self.assertSource(plannerText, contains: "case \"toggle-activity\"")
        Self.assertSource(plannerText, contains: "case \"toggle-automations\"")
        Self.assertSource(coordinatorText, contains: "case .openBrowserSession:")
        Self.assertSource(coordinatorText, contains: "case .toggleActivity:")
        Self.assertSource(coordinatorText, contains: "case .toggleAutomations:")
        Self.assertSource(plannerText, contains: "WorkspaceCommandRoutingCatalog.canRunInWorkspaceModel")
        Self.assertSource(controllerText, contains: "guard let action = QuillCodeDesktopCommandPlanner.action(for: command) else { return }")
        Self.assertSource(controllerText, contains: "commandCoordinator.run(action, performer: self)")
        Self.assertSource(controllerText, excludes: "switch command.id")
        Self.assertSource(controllerText, excludes: "switch action")
        Self.assertSource(controllerText, excludes: "case \"computer-use-open-screen-recording\"")
        Self.assertSource(controllerText, excludes: "case \"retry-last-turn\"")
    }

    func testDesktopNotifiesWhenDueAutomationsRun() throws {
        let text = try Self.desktopSourceText()
        let controllerText = try Self.desktopSourceText(named: "QuillCodeDesktopController.swift")
        let automationCoordinatorText = try Self.desktopSourceText(named: "QuillCodeDesktopAutomationCoordinator.swift")

        Self.assertSource(text, contains: "UNUserNotificationCenter")
        Self.assertSource(text, contains: "MacAutomationNotifier")
        Self.assertSource(text, contains: "QuillCodeDesktopAutomationCoordinator")
        Self.assertSource(controllerText, contains: "automationCoordinator.runDueAutomations")
        Self.assertSource(controllerText, contains: "automationCoordinator.startTicker")
        Self.assertSource(automationCoordinatorText, contains: "runDueAutomationReports")
        Self.assertSource(automationCoordinatorText, contains: "reports.forEach(notifier.deliver)")
        Self.assertSource(controllerText, excludes: "let reports = model.runDueAutomationReports()")
        Self.assertSource(controllerText, excludes: "reports.forEach(automationNotifier.deliver)")
    }
}
