/// Builds a starter `AGENTS.md` from detected project signals. The core is PURE and
/// deterministic — identical `Signals` always produce byte-identical markdown (no FS, no
/// Date/UUID, ordered arrays not Sets) — so the scaffold can be pinned by a golden test and
/// rendered identically across surfaces. The impure project scan lives in `ProjectInitScanner`.
public enum ProjectInitScaffolder {
    public enum Language: String, Sendable, Hashable, CaseIterable {
        case swift, node, python, rust, go

        public var displayName: String {
            switch self {
            case .swift: return "Swift"
            case .node: return "Node.js"
            case .python: return "Python"
            case .rust: return "Rust"
            case .go: return "Go"
            }
        }

        /// The build command, or nil when the ecosystem has no single standard build step
        /// (Node/Python builds vary per project, so the generated scaffold asks the user).
        public var buildCommand: String? {
            switch self {
            case .swift: return "swift build"
            case .node: return nil
            case .python: return nil
            case .rust: return "cargo build"
            case .go: return "go build ./..."
            }
        }

        public var testCommand: String {
            switch self {
            case .swift: return "swift test"
            case .node: return "npm test"
            case .python: return "pytest"
            case .rust: return "cargo test"
            case .go: return "go test ./..."
            }
        }
    }

    public struct Signals: Sendable, Hashable {
        public var languages: [Language]
        public var hasMakefile: Bool
        public var topLevelDirectories: [String]

        public init(languages: [Language] = [], hasMakefile: Bool = false, topLevelDirectories: [String] = []) {
            self.languages = languages
            self.hasMakefile = hasMakefile
            self.topLevelDirectories = topLevelDirectories
        }
    }

    public static func scaffold(name: String, signals: Signals) -> String {
        var sections: [String] = []
        sections.append("# \(name)")
        let generatedNotice = [
            "> Generated by QuillCode /init. Edit freely — this file is the project's agent",
            "> instructions (AGENTS.md, the Codex/Claude-CLI convention)."
        ].joined(separator: "\n")
        sections.append(generatedNotice)
        sections.append("## Project overview\n\n\(overview(name: name, signals: signals))")
        sections.append("## Build\n\n\(bulletList(buildBullets(signals)))")
        sections.append("## Test\n\n\(bulletList(testBullets(signals)))")
        sections.append("## Project layout\n\n\(bulletList(layoutBullets(signals)))")
        sections.append("## Conventions\n\n\(bulletList(conventionBullets))")
        return sections.joined(separator: "\n\n") + "\n"
    }

    private static func overview(name: String, signals: Signals) -> String {
        guard !signals.languages.isEmpty else {
            return "\(name) is a software project. Describe what it does here."
        }
        let names = signals.languages.map(\.displayName)
        return "\(name) is a \(joined(names)) project."
    }

    private static func buildBullets(_ signals: Signals) -> [String] {
        var bullets = signals.languages.compactMap { $0.buildCommand.map { "`\($0)`" } }
        if signals.hasMakefile { bullets.append("`make` (a Makefile is present)") }
        return bullets.isEmpty ? ["No build step detected. Document the build command here."] : bullets
    }

    private static func testBullets(_ signals: Signals) -> [String] {
        let bullets = signals.languages.map { "`\($0.testCommand)`" }
        return bullets.isEmpty ? ["No test command detected. Document how to run tests here."] : bullets
    }

    private static func layoutBullets(_ signals: Signals) -> [String] {
        let bullets = signals.topLevelDirectories.map { "`\($0)/`" }
        return bullets.isEmpty ? ["Document the key directories here."] : bullets
    }

    private static let conventionBullets = [
        "Keep changes small and focused.",
        "Run the test command above before finishing.",
        "Update this file when the build or test commands change."
    ]

    private static func bulletList(_ items: [String]) -> String {
        items.map { "- \($0)" }.joined(separator: "\n")
    }

    private static func joined(_ items: [String]) -> String {
        switch items.count {
        case 0: return ""
        case 1: return items[0]
        case 2: return "\(items[0]) and \(items[1])"
        default: return items.dropLast().joined(separator: ", ") + ", and " + items[items.count - 1]
        }
    }
}
